services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-dummy_key_for_local_testing_only}
      - DATABASE_URL=sqlite3:db/production.sqlite3
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    volumes:
      - ./db:/app/db
      - ./public/uploads:/app/public/uploads
      - ./log:/app/log
    command: >
      sh -c "
        echo 'Setting up production database...' &&
        bundle exec rails db:create db:migrate &&
        echo 'Running seeds...' &&
        bundle exec rails db:seed &&
        echo 'Starting server...' &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      "